### ISSUE TITLE
Previous commands preventing new commands from running correctly.

### ISSUE THREAD

**Issue by Brookke** [google/go-cmdtest#14]
I have setup a basic cobra CLI and found if you run if you run `cmd --help` before `cmd --version` the command returns help rather than version output. Suggesting that some of the state is being carried over between commands. 

CT that functions as expected
```
$ cmd --version
```

CT that doesn't function as expected
```
$ cmd --help
...
$ cmd --version
...
```

Is there any way to prevent this or is this a bug with cobra?

I have set up an example repo:
https://github.com/Brookke/go-cmdtest-repo/blob/main/testdata/version.ct

I have also tried splitting up the commands into their own ct files, but still seeing the same issue.

**Comment by vangent** [comment]
It looks to me like Cobra is keeping some internal state on a `Command`.

If you take the 

```
var cmd = &cobra.Command...
```

in your `main.go` and put it inside the `Execute` function (so that a new `cobra.Command` is created each time), the test works as expected.

I'm not sure there's anything cmdtest can do about this. You can probably work around it by either not using an in-process executor, or by making sure that the Cobra stuff is reinitialized across executions.

**Comment by Brookke** [comment]
Okay thanks for the advice @vangent
